### ISSUE TITLE
Does it really need node.js 16+?

### ISSUE THREAD

**Issue by PROPHESSOR** [peterekjs/vite-plugin-favicons#1]
https://github.com/peterekjs/vite-plugin-favicons/blob/75c97782e2085807e280036c8af8b7ef97e6e3e0/package.json#L31

Is possible to lower the version to 14+, as it is in the `favicons` library?

https://github.com/itgalaxy/favicons/blob/9091ce561a36acdecbbf9c2a16e8a57c7a131738/package.json#L51

**Comment by peterekjs** [comment]
Probably it shouldn't be a problem to lower the version to 14+. I'm going to test it first.

**Comment by peterekjs** [comment]
Fixed. You can check it on `0.1.1`
